sonar.projectKey=LICENCIA-IONIC-FRONTEND
sonar.projectName=LICENCIA IONIC FRONTEND
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**, **/www/**, **/dist/**, **/android/**, **/ios/**

sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.host.url=http://localhost:9000
sonar.token=squ_b2db2a74d8bc00e86e50077bfbcbe0f4a7eb6849